version: '3.2'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.1
    container_name: es_01
    volumes:
      - type: bind
        source: ./elasticsearch/config/elasticsearch.yml
        target: /usr/share/elasticsearch/config/elasticsearch.yml
        read_only: true
      - type: volume
        source: elasticsearch
        target: /usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx${ELASTICSEARCH_HEAP} -Xms${ELASTICSEARCH_HEAP}"
      ELASTIC_PASSWORD: changeme
      # Use single node discovery in order to disable production mode and avoid bootstrap checks.
      # see: https://www.elastic.co/guide/en/elasticsearch/reference/current/bootstrap-checks.html
      discovery.type: single-node
    networks:
      - elk



  kibana:
    #image: docker.elastic.co/kibana/kibana:7.13.1
    image: registry.gitlab.com/naphub/core-utils/kibana:v2
    #image: kibana-preserved
    volumes:
      - type: bind
        source: ./kibana/config/kibana.yml
        target: /usr/share/kibana/config/kibana.yml
        read_only: true
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch



  wireshark:
    image: ghcr.io/linuxserver/wireshark
    container_name: wireshark
    cap_add:
      - NET_ADMIN
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      #volumes:
      # - /path/to/config:/config
    ports:
      - 3000:3000 #optional
    restart: unless-stopped

      #  packetbeat:
      #    image: docker.elastic.co/beats/packetbeat:7.13.2
      #    user: root
      #    command:
      #      - --strict.perms=false
      #      - setup
      #  - E output.elasticsearch.hosts=["sec03.lab.es.aau.dk:9200"]
      #    volumes:
      #      - type: bind
      #        source: ./packetbeat/packetbeat.yml
      #        target: /usr/share/packetbeat/packetbeat.yml
      #        read_only: true
      #depends_on:
      #- "elasticsearch:" { condition: service_healthy }
      # - "kibana"
      #  depends_on:
      # elasticsearch:
      # condition: service_healthy
      #    cap_add:
      #      - NET_ADMIN
      #      - NET_RAW
      #    network_mode: host

      #    environment:
      #      - ELASTICSEARCH_URL=http://sec03.lab.es.aau.dk:9200
    #    restart: on-failure




    ######NOt working--- TO BE FIXED
#  thehive:
#    image: thehiveproject/thehive:3.5.0-1
#    volumes:
#      - type: bind
#        source: ./thehive/application.conf
#        target: /etc/thehive/application.conf
#        read_only: true
#    ports:
#      - "9000:9000"
#    networks:
#      - elk
#    depends_on:
#      - elasticsearch

networks:
  elk:
    driver: bridge

volumes:
  elasticsearch: