## Default Kibana configuration from Kibana base image.
## https://github.com/elastic/kibana/blob/master/src/dev/build/tasks/os_packages/docker_generator/templates/kibana_yml.template.ts
#
server.name: kibana
server.host: 0.0.0.0
elasticsearch.hosts: [ "http://elasticsearch:9200" ]
monitoring.ui.container.elasticsearch.enabled: true

## X-Pack security credentials
#
#elasticsearch.username: elastic
#elasticsearch.password: changeme

#FLeet settingsls


#xpack.fleet.enabled: true
xpack.fleet.registryUrl: "http://registry:8080"
xpack.fleet.agents.tlsCheckDisabled: true
xpack.encryptedSavedObjects.encryptionKey: "min-32-byte-long-strong-encryption-key"


elasticsearch.username: "elastic"
elasticsearch.password: "changeme"



#xpack.fleet.agents.enable: true

